spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/breadroll-mall?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:com/qiu/mapper/*.xml
  type-aliases-package: com.qiu.entity
  configuration:
    mapUnderscoreToCamelCase: true